api/src/services/__tests__/competenciesService.ts
api/src/services/competenciesService.ts

This change creates a competencies service function and tests to fetch competencies list with pagination. 
This is the 1st PR covering the query portion. for ticket #272

Add competencies services and test 

---

api/src/middleware/__tests__/competenciesRouter.ts
api/src/middleware/competenciesRouter.ts
api/src/server.ts
api/src/services/__tests__/competenciesService.ts
api/src/services/competenciesService.ts

- Add `countCompetencies` function into competencies service
- Add test for `countCompetencies` function in competencies service test
- Add `competenciesRouter`  get a request to show a paginated list of competencies
- Add `competenciesRouter`  get request test to show a paginated list of competencies and check/throw errors when counting or listing competencies.
- Add `competencies` routes in server file 
Resolves #272

Add api to fetch competencies

---

api/README.md
api/src/middleware/__tests__/competenciesRouter.ts
api/src/middleware/competenciesRouter.ts
api/src/services/__tests__/competenciesService.ts
api/src/services/competenciesService.ts

- Add and test a function to insert a given competency into the `competencies` table and to the authoring principal's `model_competencies` table.
- Add and test POST method to the `/competencies` API endpoint.
Resolves #274

Add api endpoint to create new competencies

---

webapp/src/components/App.tsx
webapp/src/components/CompetenciesPage.tsx
webapp/src/components/Competency.tsx
webapp/src/types/api.d.ts

Adds a `/competencies` route to the webapp that displays a competencies page with data from the `/competencies` endpoint in the API.
Resolves #273

Make competencies viewable from the app

---

.github/workflows/build_and_publish_images.yml
docker-compose.production.yml
nginx/production/nginx.conf
webapp/Dockerfile
webapp/default.conf

Serve the webapp from its own container in production. Uses `try_files`, falling back to `index.html`, to address #292.
After this is shipped, `webapp/netlify.toml` can be removed and that site deleted, since the app will be built and served from our infrastructure instead.
Another step along the way to addressing #90.

Build and push a production webapp image to replace Netlify webapp

---

.github/workflows/build_and_publish_images.yml

Use https instead of http for api to prevent mixed content cors error.

Use https for api origin in webapp image

---

.github/workflows/build_and_publish_images.yml
docker-compose.production.yml

Build a flyway image on release, and run `flyway migrate` as a service when the production stack is deployed.
This is a big step toward #90.

Run migrations in a container as a service in production

---

.github/CODEOWNERS
webapp/netlify.toml

In simplifying the deployment, the webapp is published in an image that is run on the Docker stack now, so there's no need for any of the Netlify config. The Netlify site that previously hosted the webapp has been deleted.
Just another step in #90.

Remove netlify config since webapp is published in an image now

---

docker-compose.production.yml

When deploying the production stack to the swarm, the flyway service continuously restarts even though it exits with `0`. Since we only want the migrations to run once per deploy, this is undesirable. Instead, flyway will have to be run as a one-off elsewhere in the pipeline. Until then, removing it from the stack config so we can deploy other stuff.
One step back in #90.

Remove flyway service in prod stack because it keeps restarting

---

api/src/middleware/authRouter.ts
api/src/server.ts
api/src/services/__tests__/configService.ts
api/src/services/__tests__/githubApiService.ts
api/src/services/configService.ts
api/src/services/db.ts
api/src/services/githubApiService.ts

Replaces uses of environment variables in the api with a service that first checks to see whether a Docker secret exists with the given key, then falls back to environment variables (for dev and test).
Resolves #303.

Optionally get config from secrets files

---

docker-compose.production.yml

Takes the environment variables that the production api service was using that contain secret values and configures them to be read from Docker secrets instead. 
Resolves #308.

Swap prod secrets from environment variables to Docker secrets

---

api/src/middleware/__tests__/competenciesRouter.ts
api/src/middleware/competenciesRouter.ts
api/src/services/__tests__/competenciesService.ts
api/src/services/competenciesService.ts

This is partial resolution for ticket #277.
updateCompetency function and test for querying a specific competency for a user who authored it.

Add api endpoint for updating competencies

---

api/src/services/__tests__/competenciesService.ts
api/src/services/competenciesService.ts
webapp/src/components/CompetenciesPage.tsx
webapp/src/components/Competency.tsx
webapp/src/components/CreateCompetencyForm.tsx
webapp/src/components/CreateOrUpdateCompetencyForm.tsx
webapp/src/types/api.d.ts

Refactors the Create Competency Form in order to allow users to edit competencies they've authored.
Adds UI changes in order to populate edit form.

Allow principal authors to edit competencies

---

webapp/package.json
webapp/yarn.lock

Upgrades webapp to use react-scripts 5. It was a pretty easy upgrade because the app is still very small.
Also upgrades all the other dependencies to their latest versions. This should address a lot of the Dependabot warnings mentioned in #260.
Resolves #259.

Upgrade webapp to use react-scripts 5

---

api/src/server.ts
webapp/src/helpers/__tests__/useSocket.ts
webapp/src/helpers/useSocket.ts

- Convert the usage of `expressSession` into `sessionMiddleware` to be used by Socket.IO
- Socket.IO is able to access the principalId through the cookie headers after it's sent by the `useSocket` helper function
- Express route handler have access to Socket.IO instance
Resolves the last few tasks on #174

Update express interactions with socket.IO

---

.github/workflows/deploy.yml
db/Dockerfile

Downgrade flyway to version 6, which is able to read config from stdin.
Send flyway config via stdin during deployment instead of uploading a config file.
Resolves #322.

Send flyway config using stdin during deployment

---

api/src/server.ts

`ts-node` runs the tests just fine, but `tsc` breaks with the type that was defined.
https://github.com/OpenTree-Education/rhizone-lms/runs/5413941756?check_suite_focus=true
So, `@ts-ignore` to unblock the pipeline until we figure out what happened.

Ignore types for socket.request for now; it breaks the build

---

api/src/server.ts

Reverts OpenTree-Education/rhizone-lms#328 and fixes the issue that broke the build.
Original build output.
```
~/projects/rhizone-lms/api (revert-328-177-types-broke-the-build) $ yarn build
yarn run v1.22.17
$ tsc
node_modules/@types/express-serve-static-core/index.d.ts:369:18 - error TS2320: Interface 'Request<P, ResBody, ReqBody, ReqQuery, Locals>' cannot simultaneously extend types 'IncomingMessage' and 'Request'.
Named property 'session' of types 'IncomingMessage' and 'Request' are not identical.
369 export interface Request<
~~~~~~~
Found 1 error.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Fixed build output.
```
~/projects/rhizone-lms/api (revert-328-177-types-broke-the-build) $ yarn build
yarn run …
```

Revert "Ignore types for socket.request for now; it breaks the build"

---

db/README.md
db/migration/V007__backfill_journal_entry_reflections.sql
db/tasks/T001__update_migration_7_checksum.sql

In order to make it so that new developers can run all the migrations using the downgraded Flyway version, one of the migrations had to be updated. Changing a migration file updates the checksum of that file, which will cause validation of the schema to fail when Flyway runs in production.
A new `db/tasks` folder was created to manage one-off tasks to be run against the production database. A new task was created to update the checksum of the changed migration in production so that it will pass validation.
Resolves #325.

Make all migrations run on Flyway 6

---

api/src/middleware/meetingsRouter.ts
api/src/middleware/routerTestUtils.ts
api/src/services/__tests__/meetingsService.ts
api/src/services/meetingsService.ts

- When a meeting note is successfully created, it will emit a socket message to the room associated with the meeting. 
- Add test cases in `meetingService` to test for new query data and null values
Resolves #175

Upon successful meeting note creation, socket message is emitted to the associated room

---

api/src/services/__tests__/meetingsService.ts
api/src/services/meetingsService.ts

Changes the Meeting Notes query to order agenda items with `agenda_owning_participant_id` as`null` last.
Resolves #316.

Add orderBy to meetingNotes query so action items show up last

---

.github/workflows/deploy.yml

When Rhizone is being deployed, the dialog includes a new input, "Renew TLS certificates?", which, when checked, will take Nginx offline and renew the TLS certificates before redeploying the services.
Resolves #251.

Add optional step to deploy workflow that renews TLS certificates

---

docker-compose.yml

This adds a health check to the MySQL container, and it modifies the Flyway container to tell Docker to wait until the MySQL container is *listening* before starting the Flyway container.
I'm proposing to modify the `docker-compose.yml` file we all use to bring up our local development environments to delay launching the Flyway container until the MySQL container is considered 'healthy'; that is, when the MySQL container is listening for incoming connections. This should improve the reliability of the database migrations immensely, as long as the MySQL daemon can start listening within 120 seconds (two minutes) from container start and respond to the health check in a way that Docker understands.
If and only if that's the case will Docker execute the Flyway container to perform the …

#357 Improve Flyway Reliability

---

api/src/middleware/__tests__/competenciesRouter.ts
api/src/middleware/competenciesRouter.ts

Closes #374 
This PR creates an API route at `/competencies/categories` that returns all categories in the database in an array, with each category object containing an array of their competencies. This route can be used on the frontend to render the competency categories and each competency in each category on the visualization table. 
This is a screenshot of the returned categories and competencies in JSON:
Here is a screenshot of the passing tests:

Create route to fetch categories with their competencies

---

api/Dockerfile
webapp/Dockerfile

Resolves #410.
This should improve quality of life for users with slower internet connections, but should have no impact on any others. Previously discussed with Davey.
This modifies the Dockerfile for each of the affected docker images (`api` and `webapp`) to increase Yarn's network timeout during install to 10 minutes (600,000 milliseconds).

#410 Increase network timeout value to 10 minutes

---

db/migration/V019__create_programs.sql

Co-authored by: SanazDn <sanaz142@yahoo.com>
Co-authored by: Ruthie Rabinovitch <62635544+rrabinovitch@users.noreply.github.com>
This PR adds a migration file to set up tables for `curriculums`, `programs`, `activity_types`, `activities`, and `participant_activities`. The migration file also includes examples of `activity_type` records to populate the `activity_types` table.
For `start_date` and `end_date` in the `programs` table, we used the SQL `DATE` type, which uses the `YYYY-MM-DD` format.
For `start_time` and `end_time` in the `activities` table, we used the SQL `TIME` type, which uses the `hh:mm:ss` format. Afternoon times should be represented in 24 hr structure (eg, 3pm would translate to `15:00:00`)

#412 set up programs db infrastructure

---

db/migration/V020__insert_default_activities.sql

Co-authored by: Phoebe Yu(@phoebehala)
Co-authored by: Veranika Karpava(@veranika-karpava)
This pull request resolves https://github.com/OpenTree-Education/rhizone-lms/issues/413.
The migration file includes default data of activities and curriculums records to populate curriculums and activities tables.

#413 Insert default curriculum, including activities

---

api/package.json
api/yarn.lock
webapp/package.json
webapp/yarn.lock

This resolves #440 by upgrading `socket.io` in our API and `socket.io-client` in our webapp to versions not affected by the CVE.

#440 Update packages to address security vulnerability

---

webapp/src/components/ProgramCalendar.tsx

This PR resolves the #445 by enabling the `react-big-calendar` to show a popup with all the activities of the selected date when the user clicks '+ more' in the calendar's month view. The activities in the popup are also clickable and show the activity dialog with activity information when clicked.

#445 Add popup in Calendar to enable the show more via popup feature in month view

---

webapp/src/components/ProgramCalendar.tsx

Added "All Day" label to the week/day's view first row on the left.

#448 add all day label to the calendar

---

webapp/src/components/Navbar.tsx

Add a home icon to the Navbar for the User to click and be rerouted to the home page.
Add styling to the Rhizone logo so when the user hover the mouse over it so they will be more aware that they can use the logo to go to the main page.
https://user-images.githubusercontent.com/98124157/204907165-ea8d1670-3c36-40b4-9064-8a7ad8d3d07b.mov

#446 Add options for addressing "back"/"home" button feedback

---

webapp/src/components/ProgramActivityDialog.tsx

This makes some tweaks to the design of the Dialog to make it a little easier to read, ensuring consistent spacing and making it more flexible to extend in the future.
I was going to wrap the dates in HTML5 `<time>` elements, but I'm not sure that's the best approach as of now. I'll think about that later.

#465 Refine the Dialog design

---

db/migration/V019__create_programs.sql

This resolves #474 by adding a unique constraint to the `participant_activities` table so that we can't possibly insert a duplicate combination of (program_id, activity_id, and participant_id) into the table.

#474 Add unique constraint to participant_activities

---

api/src/middleware/__tests__/programsRouter.ts
api/src/middleware/programsRouter.ts

This PR resolves #464 by adding error handling into the `programsRouter.get('/')` function. A respective test block was added to the programs router test file.

#464 Add error handling to programsRouter GET function 

---

api/src/models.d.ts
api/src/services/__tests__/programsService.ts
api/src/services/programsService.ts

This resolves  #454 by:
- A `getParticipantActivityId` function returns the participant activity ID if it exists, otherwise it returns null.
- A `getParticipantActivityCompletion` function returns the completion status (either true or false) of the specific activity.
- A `setParticipantActivityCompletion` function is to set/update the completion status of the specific activity.
-  The JsDoc function headers for each of functions above.
-  The JEST test functions for each of functions above.

#454 Add service file functions to update `participant_activities` completion status

---

webapp/src/components/ProgramCalendar.tsx

The colour and height of all day activity updated in the calendar.

#471 Change the colour of all-day activities

---

api/src/services/__tests__/programsService.ts
api/src/services/programsService.ts

This issue resolves #481 by:
`setParticipantActivityCompletion()` return the participantActivityId and the completion status (true or false) of an inserted row in the table
Test functions updated to reflect the above service function changed

#481 Setter service function should return correct values

---

api/src/middleware/__tests__/programsRouter.ts
api/src/middleware/programsRouter.ts

This PR resolves #455 by creating getter and setter functions for individual an participantActivity's completion status, as well as tests for these new functions.
Manually tested on local machine:
- GET `http://api.rhi.zone-development/programs/activityStatus/1/1` returned `{"data":{"programId":1,"activityId":1,"completed":false}}`
- POST `http://api.rhi.zone-development/programs/activityStatus/1/1` with request body `{"completed": true}` returned `{"data":{"completed":false}}`

#455 programs router supports retrieval and updating of participant activities completion status

---

db/migration/V020__insert_default_activities.sql

Mentor assessments are handled through the exit survey, so this update resolves #483 by updating the migration file to remove the assessments and final self-evaluation, and it wraps them into the exit survey.

#483 Remove mentor assessments from example data

---

api/src/middleware/programsRouter.ts
api/src/models.d.ts
api/src/services/__tests__/programsService.ts
api/src/services/programsService.ts
db/migration/V020__insert_default_activities.sql

These changes resolve #488 by doing the following:
- This removes Cohort 5 from the database migration.
- This pre-fills the `participant_activities` table for each user when they load the calendar page for the first time.
The latter functionality was achieved in code rather than with a stored procedure / migration. This was done in order to adapt best to both environments—live and development—and for code maintainability and testing purposes. Additionally, this minimizes the number of database inserts that need to be done by doing them only on an as-needed basis.
To reiterate, this functionality is only here until we build an admin feature for the participant activities and can associate users with specific programs. When that happens, this code can be removed.
This pull request also …

#488 Pre-fill participant activities for existing users upon calendar page load
