OpenTree-Education/rhizone-lms

- api/src/services/__tests__/competenciesService.ts
- api/src/services/competenciesService.ts
Adds a function to the competenciesService file which creates competencies into the database.
Adds a describe block and test for the function.
This is PR is one part of issue #274
> Add function to create competencies and test

- api/src/services/__tests__/competenciesService.ts
- api/src/services/competenciesService.ts
add orderby for label and id in ascending order for competency list
Resolves #291
> Add OrderBy to list of Competencies

- .github/workflows/deploy.yml
This GitHub Actions workflow uses ssh to run the deploy steps on the production server. Namely, run the database migrations and then deploy the docker stack.
Resolves #90, finally.
> Push button, deploy production

- api/src/server.ts
- api/src/services/__tests__/meetingsService.ts
- api/src/services/meetingsService.ts
Add sockets to the meeting room
> Add sockets to meeting rooms

- .github/workflows/deploy.yml
Add `sudo` to `certbot renew` to run it as root.
> Certbot needs to run as root

- webapp/src/components/App.tsx
- webapp/src/components/Navbar.tsx
- webapp/src/components/Profile.tsx
This PR addresses issue #345.
Add a route for the profile, add an icon to the navbar, and add a home link to the logo.
> 345 add profile icon with route

- webapp/package.json
- webapp/src/components/Profile.tsx
- webapp/yarn.lock
This resolves issue #348.
Add links to Journal and Competency features to LMS on the profile page. The Competency button linked to Competency page and the journal button linked to home page.
We did not create a link to progress bar as it will be on the profile page after #349 is solved.
> #348 Add profile links to lms features

- webapp/src/components/CompetencyRatings.tsx
- webapp/src/components/Profile.tsx
- webapp/src/components/ProgressBar.tsx
- webapp/src/components/__tests__/ProgressBar.test.tsx
Addresses #349.
Users can see a progress view with two types of trackers. First, a circular rating to showcase competencies; second, a linear bar to showcase progression through a program.
The circular and linear progress are hardcoded for now but designed to fetch progress from a program table.
> #349 Add progress bar and rating tracker component

- webapp/src/components/Profile.tsx
Closes issue #350.
Add personalized greetings for the user based on the time of the day and thier browser language. For code organization, we separated functions to the `greeting` file in the helper folder. We included English, French and Japanese for now. Anyone can add more in the future.
The greeting defaults to English if the browser language is not hardcoded.
> #350 Personalized greetings for the user

- docker-compose.yml
Reverts OpenTree-Education/rhizone-lms#358
> Revert "#357 Improve Flyway Reliability"

- webapp/src/components/App.tsx
- webapp/src/components/Navbar.tsx
- webapp/src/components/Profile.tsx
Reverts OpenTree-Education/rhizone-lms#351
> Revert "#345 add profile icon with route"

- docker-compose.yml
Reverts OpenTree-Education/rhizone-lms#389
> Revert "Revert "#357 Improve Flyway Reliability""

- api/src/services/__tests__/competenciesService.ts
- webapp/src/components/Meeting.tsx
Closes issue #396.
Change variable names to camel case.
> #396 Change variable names to camel case

- api/package.json
- webapp/package.json
#393 ESLint config changes
The linter checks the files based on the formatting standards which considered the camelCase for variables and a new line at end of files.
> 393 ESLint config changes

- webapp/src/components/App.tsx
- webapp/src/components/CalendarPage.tsx
- webapp/src/components/Navbar.tsx
- webapp/yarn.lock
This pull request resolves #414 . It adds a calendar icon in the navbar that links to the calendar page. The existing icon to meetings has been changed to a people icon.
> #414 Add calendar icon in the navbar which links to the calendar page

- webapp/src/components/Activity.tsx
- webapp/src/components/CalendarPage.tsx
- webapp/src/components/Program.tsx
Co-authored by: @wendyyng 
Co-authored by: @phoebehala 
Co-authored by: @veranika-karpava  
This pull request resolve #427. Created the Programs and Activities components that display the program data (default program and its activities) fetched from the program API. The Activities component acts as a stepping stone for displaying the program activities data in the calendar. It may be modified or replaced by calendar related components in future commits.
> #427 Make a graphical representation of the programs and activities on the frontend side

- api/src/middleware/__tests__/programsRouter.ts
- api/src/middleware/programsRouter.ts
- api/src/services/__tests__/programsService.ts
- api/src/services/programsService.ts
Co-author: @ChainShoe-Z
Co-author: @veranika-karpava
Co-author: @seidior
This pull request serves both as an enhancement of the code that was contributed in #415 as well as adds a new `listProgramsWithActivities` function in the `programsService.ts` file. It resolves issue #429 and should wrap up all remaining tasks in the back-end code to support this feature's rollout.
The code in `programsService.ts` was further refactored to have similar functions follow a parallel structure in their function bodies and to further build out the helper functions. Code was reorganized and documentation was added to improve readability of the file overall. Tests were modified to support the code changes in `programsService.ts` and `programsRouter.ts`.
These changes add the `listProgramsWithActivities` …
> #429 Add new listProgramsWithActivities function and wrap up backend modifications

- db/migration/V019__create_programs.sql
- db/migration/V020__insert_default_activities.sql
Resolves issue #437 not by only modifying the errors but by enhancing all the sample data with more thorough titles and descriptions. I wrote code to generate the SQL to insert for the example curriculum activities to ensure every activity is placed on the correct day and at the correct times.
Updates all the activities to better align their names, descriptions, and times with the current cohort’s activities, and add any missing activities.
Adds an additional curriculum value (“Custom Curriculum”) to allow for unstructured curricula.
Adds an additional program value (“Cohort 5”) with some non-final dates so we have more than one program with which we test the front-end features.
Updates the list of program activities to include more types of activities.
Improves spacing and layout so SQL …
> #437 Modifications to curriculum activities

- webapp/src/components/ProgramCalendar.tsx
- webapp/src/index.css
Capitalized "all day" text in  agenda's view
> #462 Rewrite class for all day text

- webapp/src/components/ProgramActivityDialog.tsx
- webapp/src/components/ProgramCalendar.tsx
- webapp/src/types/api.d.ts
_What does this pull request propose to change?_
Adding the corresponding program for the activity pop-out window
> #453 Add program name in activity details Dialog

- webapp/src/index.css
Resolved  #449 issue with text cursor showing up while hovering on the activities in the agenda. The cursor changes to a hand pointer now.
> #449 Hover over the activities in agenda shows hand pointer

- webapp/src/components/ProgramPicker.tsx
- webapp/src/components/ProgramsPage.tsx
This pull request resolves issue #490. 
Make code readable and clean.
> #490 Import useState, useEffect, Dispatch, setStateAction from React in the ProgramPicker, the ProgramPage

- api/src/services/__tests__/programsService.ts
- api/src/services/programsService.ts
- webapp/src/components/ProgramActivityDialog.tsx
- webapp/src/components/ProgramCalendar.tsx
- webapp/src/components/ProgramsPage.tsx
- webapp/src/types/api.d.ts
This resolves #470 by:
- Retrieving the completed status of all assignments in a program at once.
- Addressing a type issue with the return type from a backend service file function.
> #470 Get all assignments and their completion at once in webapp

- .github/ISSUE_TEMPLATE/1.bug_report.yml
This resolves #501 by removing the unnecessary main checkbox addition from the previous commit.
> #501 Remove main checkbox
